const express = require('express');
const router = express.Router();
const { v4: uuidv4 } = require('uuid');

// In-memory branding store
const brandingStore = new Map([
  ['default', {
    id: 'default',
    name: 'Default White Label',
    logo: null,
    primaryColor: '#10B981',
    secondaryColor: '#3B82F6',
    accentColor: '#8B5CF6',
    fontFamily: 'Inter, system-ui, sans-serif',
    companyName: 'OpenSEO',
    companyUrl: 'https://openseo.dev',
    footerText: 'Generated by OpenSEO',
    active: true,
    createdAt: new Date().toISOString()
  }]
]);

/**
 * GET /api/branding
 * List all branding configurations
 */
router.get('/', (req, res) => {
  const brandings = Array.from(brandingStore.values()).map(b => ({
    id: b.id,
    name: b.name,
    logo: b.logo,
    primaryColor: b.primaryColor,
    active: b.active
  }));
  
  res.json({ success: true, brandings, total: brandings.length });
});

/**
 * GET /api/branding/:id
 * Get branding by ID
 */
router.get('/:id', (req, res) => {
  const branding = brandingStore.get(req.params.id);
  
  if (!branding) {
    return res.status(404).json({ error: 'Branding not found' });
  }
  
  res.json({ success: true, branding });
});

/**
 * POST /api/branding
 * Create new branding configuration
 */
router.post('/', (req, res) => {
  const { name, logo, primaryColor, secondaryColor, accentColor, fontFamily, companyName, companyUrl, footerText } = req.body;
  
  if (!name) {
    return res.status(400).json({ error: 'Name required' });
  }
  
  const branding = {
    id: 'brand_' + uuidv4().slice(0, 8),
    name,
    logo: logo || null,
    primaryColor: primaryColor || '#10B981',
    secondaryColor: secondaryColor || '#3B82F6',
    accentColor: accentColor || '#8B5CF6',
    fontFamily: fontFamily || 'Inter, system-ui, sans-serif',
    companyName: companyName || '',
    companyUrl: companyUrl || '',
    footerText: footerText || 'Generated by OpenSEO',
    active: false,
    createdAt: new Date().toISOString()
  };
  
  brandingStore.set(branding.id, branding);
  
  res.status(201).json({ success: true, branding });
});

/**
 * PUT /api/branding/:id
 * Update branding
 */
router.put('/:id', (req, res) => {
  const branding = brandingStore.get(req.params.id);
  
  if (!branding) {
    return res.status(404).json({ error: 'Branding not found' });
  }
  
  const { name, logo, primaryColor, secondaryColor, accentColor, fontFamily, companyName, companyUrl, footerText, active } = req.body;
  
  if (name) branding.name = name;
  if (logo !== undefined) branding.logo = logo;
  if (primaryColor) branding.primaryColor = primaryColor;
  if (secondaryColor) branding.secondaryColor = secondaryColor;
  if (accentColor) branding.accentColor = accentColor;
  if (fontFamily) branding.fontFamily = fontFamily;
  if (companyName !== undefined) branding.companyName = companyName;
  if (companyUrl !== undefined) branding.companyUrl = companyUrl;
  if (footerText !== undefined) branding.footerText = footerText;
  if (active !== undefined) branding.active = active;
  
  brandingStore.set(branding.id, branding);
  
  res.json({ success: true, branding });
});

/**
 * DELETE /api/branding/:id
 * Delete branding
 */
router.delete('/:id', (req, res) => {
  if (!brandingStore.has(req.params.id)) {
    return res.status(404).json({ error: 'Branding not found' });
  }
  
  if (req.params.id === 'default') {
    return res.status(400).json({ error: 'Cannot delete default branding' });
  }
  
  brandingStore.delete(req.params.id);
  res.json({ success: true, message: 'Branding deleted' });
});

/**
 * POST /api/branding/:id/preview
 * Preview branding
 */
router.post('/:id/preview', (req, res) => {
  const branding = brandingStore.get(req.params.id);
  
  if (!branding) {
    return res.status(404).json({ error: 'Branding not found' });
  }
  
  const preview = {
    id: branding.id,
    name: branding.name,
    css: generatePreviewCSS(branding),
    sampleHtml: generateSampleHTML(branding)
  };
  
  res.json({ success: true, preview });
});

/**
 * POST /api/branding/:id/logo
 * Upload logo
 */
router.post('/:id/logo', (req, res) => {
  const branding = brandingStore.get(req.params.id);
  
  if (!branding) {
    return res.status(404).json({ error: 'Branding not found' });
  }
  
  const { logoUrl, logoBase64 } = req.body;
  
  if (!logoUrl && !logoBase64) {
    return res.status(400).json({ error: 'Logo URL or base64 required' });
  }
  
  branding.logo = logoBase64 || logoUrl;
  brandingStore.set(branding.id, branding);
  
  res.json({ success: true, logo: branding.logo });
});

function generatePreviewCSS(branding) {
  return `
    .report-header { background: ${branding.primaryColor}; }
    .report-title { color: ${branding.primaryColor}; }
    .report-accent { color: ${branding.accentColor}; }
    .report-footer { border-top: 2px solid ${branding.primaryColor}; }
    body { font-family: ${branding.fontFamily}; }
  `;
}

function generateSampleHTML(branding) {
  return `
    <div class="report" style="font-family: ${branding.fontFamily}">
      <div class="report-header" style="background: ${branding.primaryColor}; padding: 20px;">
        <img src="${branding.logo || '/placeholder-logo.png'}" alt="Logo" style="height: 40px;">
        <h1 style="color: white;">Sample Report</h1>
      </div>
      <div class="report-content">
        <p>Generated with ${branding.companyName || 'OpenSEO'}</p>
      </div>
      <div class="report-footer" style="border-top: 2px solid ${branding.primaryColor};">
        <small>${branding.footerText}</small>
      </div>
    </div>
  `;
}

module.exports = router;
